### ISSUE TITLE
koyeb生成的url访问404

### ISSUE THREAD

**Issue by AlterGu** [aurorax-neo/free-gpt3.5-2api#11]
你好
我使用koyeb部署该项目后，在测试接口时报404，请求命令如下
```bash
curl --location --request -X POST 'https://ridiculous-sephira-dogemaster.koyeb.app/v1/chat/completions' \
--header 'Authorization: Bearer abc' \
--header 'Content-Type: application/json' \
-d '{ \
    "model": "gpt-3.5-turbo",\
    "messages": [\
        {\
            "role": "user",\
            "content": "西红柿炒钢丝球怎么做?"\
        }\
    ],\
    "stream": false\
}'
```

**Comment by aurorax-neo** [comment]
> 你好 我使用koyeb部署该项目后，在测试接口时报404，请求命令如下
> 
> ```shell
> curl --location --request -X POST 'https://ridiculous-sephira-dogemaster.koyeb.app/v1/chat/completions' \
> --header 'Authorization: Bearer abc' \
> --header 'Content-Type: application/json' \
> -d '{ \
>     "model": "gpt-3.5-turbo",\
>     "messages": [\
>         {\
>             "role": "user",\
>             "content": "西红柿炒钢丝球怎么做?"\
>         }\
>     ],\
>     "stream": false\
> }'
> ```

部署的区域是选择的 美国吗 我这里测试正常，如果可以提供一下更详细的日志

**Comment by AlterGu** [comment]
> > 你好 我使用koyeb部署该项目后，在测试接口时报404，请求命令如下
> > ```shell
> > curl --location --request -X POST 'https://ridiculous-sephira-dogemaster.koyeb.app/v1/chat/completions' \
> > --header 'Authorization: Bearer abc' \
> > --header 'Content-Type: application/json' \
> > -d '{ \
> >     "model": "gpt-3.5-turbo",\
> >     "messages": [\
> >         {\
> >             "role": "user",\
> >             "content": "西红柿炒钢丝球怎么做?"\
> >         }\
> >     ],\
> >     "stream": false\
> > }'
> > ```
> 
> 部署的区域是选择的 美国吗 我这里测试正常，如果可以提供一下更详细的日志

你好，区域是美国(Washington, D.C) ,奇怪的是日志突然出现大量
```
2024-04-18 04:51:58	error	chat/gpt35.go:71	If this error persists, your country may not be supported yet.
2024-04-18 04:51:58	error	chat/gpt35.go:72	If your country was the issue, please consider using a U.S. PROXY.
```

**Comment by AlterGu** [comment]
> > 你好 我使用koyeb部署该项目后，在测试接口时报404，请求命令如下
> > ```shell
> > curl --location --request -X POST 'https://ridiculous-sephira-dogemaster.koyeb.app/v1/chat/completions' \
> > --header 'Authorization: Bearer abc' \
> > --header 'Content-Type: application/json' \
> > -d '{ \
> >     "model": "gpt-3.5-turbo",\
> >     "messages": [\
> >         {\
> >             "role": "user",\
> >             "content": "西红柿炒钢丝球怎么做?"\
> >         }\
> >     ],\
> >     "stream": false\
> > }'
> > ```
> 
> 部署的区域是选择的 美国吗 我这里测试正常，如果可以提供一下更详细的日志

区域是选的`Washington, D.C`

访问ping的时候回应`pong`是正常的，访问根路径返回`Hello,This is free-gpt3.5-2api.`也是正常的，就是访问`/v1/chat/completions`出现`404`

环境变量设置如下
```
AUTHORIZATIONS=xiaolaoban
AUTH_ED=180
AUTH_USE_COUNT=5
BIND=0.0.0.0
LOG_LEVEL=debug
POOL_MAX_COUNT=5
PORT=3040
PROXY=
```


日志级别改成debug了，但是控制台好像没有出现很多日志，只有以下这些刚启动时的日志.
```
Instance created. Preparing to start...
Instance is starting. Propagating network configuration...
Network configuration propagated
2024-04-18 05:23:04	info	pool/gpt35pool.go:37	PoolMaxCount: 5, AuthUseCount: 5, AuthExpirationDate: 180, Init Gpt35Pool...
2024-04-18 05:23:04	info	app/main.go:23	Server started on http://127.0.0.1:3040
Instance is healthy. All health checks are passing.
```

**Comment by AlterGu** [comment]
> > > 你好 我使用koyeb部署该项目后，在测试接口时报404，请求命令如下
> > > ```shell
> > > curl --location --request -X POST 'https://ridiculous-sephira-dogemaster.koyeb.app/v1/chat/completions' \
> > > --header 'Authorization: Bearer abc' \
> > > --header 'Content-Type: application/json' \
> > > -d '{ \
> > >     "model": "gpt-3.5-turbo",\
> > >     "messages": [\
> > >         {\
> > >             "role": "user",\
> > >             "content": "西红柿炒钢丝球怎么做?"\
> > >         }\
> > >     ],\
> > >     "stream": false\
> > > }'
> > > ```
> > 
> > 
> > 部署的区域是选择的 美国吗 我这里测试正常，如果可以提供一下更详细的日志
> 
> 区域是选的`Washington, D.C`
> 
> 访问ping的时候回应`pong`是正常的，访问根路径返回`Hello,This is free-gpt3.5-2api.`也是正常的，就是访问`/v1/chat/completions`出现`404`
> 
> 环境变量设置如下
> 
> ```
> AUTHORIZATIONS=xiaolaoban
> AUTH_ED=180
> AUTH_USE_COUNT=5
> BIND=0.0.0.0
> LOG_LEVEL=debug
> POOL_MAX_COUNT=5
> PORT=3040
> PROXY=
> ```
> 
> 日志级别改成debug了，但是控制台好像没有出现很多日志，只有以下这些刚启动时的日志.
> 
> ```
> Instance created. Preparing to start...
> Instance is starting. Propagating network configuration...
> Network configuration propagated
> 2024-04-18 05:23:04	info	pool/gpt35pool.go:37	PoolMaxCount: 5, AuthUseCount: 5, AuthExpirationDate: 180, Init Gpt35Pool...
> 2024-04-18 05:23:04	info	app/main.go:23	Server started on http://127.0.0.1:3040
> Instance is healthy. All health checks are passing.
> ```

现在刷新了不少日志
```2024-04-18 06:35:04	error	chat/gpt35.go:70	Failed to get authorization: StatusCode: 401
2024-04-18 06:35:04	error	chat/gpt35.go:71	If this error persists, your country may not be supported yet.
2024-04-18 06:35:04	error	chat/gpt35.go:72	If your country was the issue, please consider using a U.S. PROXY.
```
但我区域已经选美国了

**Comment by aurorax-neo** [comment]
> > > > 你好 我使用koyeb部署该项目后，在测试接口时报404，请求命令如下
> 
> > > > ```shell
> 
> > > > curl --location --request -X POST 'https://ridiculous-sephira-dogemaster.koyeb.app/v1/chat/completions' \
> 
> > > > --header 'Authorization: Bearer abc' \
> 
> > > > --header 'Content-Type: application/json' \
> 
> > > > -d '{ \
> 
> > > >     "model": "gpt-3.5-turbo",\
> 
> > > >     "messages": [\
> 
> > > >         {\
> 
> > > >             "role": "user",\
> 
> > > >             "content": "西红柿炒钢丝球怎么做?"\
> 
> > > >         }\
> 
> > > >     ],\
> 
> > > >     "stream": false\
> 
> > > > }'
> 
> > > > ```
> 
> > > 
> 
> > > 
> 
> > > 部署的区域是选择的 美国吗 我这里测试正常，如果可以提供一下更详细的日志
> 
> > 
> 
> > 区域是选的`Washington, D.C`
> 
> > 
> 
> > 访问ping的时候回应`pong`是正常的，访问根路径返回`Hello,This is free-gpt3.5-2api.`也是正常的，就是访问`/v1/chat/completions`出现`404`
> 
> > 
> 
> > 环境变量设置如下
> 
> > 
> 
> > ```
> 
> > AUTHORIZATIONS=xiaolaoban
> 
> > AUTH_ED=180
> 
> > AUTH_USE_COUNT=5
> 
> > BIND=0.0.0.0
> 
> > LOG_LEVEL=debug
> 
> > POOL_MAX_COUNT=5
> 
> > PORT=3040
> 
> > PROXY=
> 
> > ```
> 
> > 
> 
> > 日志级别改成debug了，但是控制台好像没有出现很多日志，只有以下这些刚启动时的日志.
> 
> > 
> 
> > ```
> 
> > Instance created. Preparing to start...
> 
> > Instance is starting. Propagating network configuration...
> 
> > Network configuration propagated
> 
> > 2024-04-18 05:23:04	info	pool/gpt35pool.go:37	PoolMaxCount: 5, AuthUseCount: 5, AuthExpirationDate: 180, Init Gpt35Pool...
> 
> > 2024-04-18 05:23:04	info	app/main.go:23	Server started on http://127.0.0.1:3040
> 
> > Instance is healthy. All health checks are passing.
> 
> > ```
> 
> 
> 
> 现在刷新了不少日志
> 
> ```2024-04-18 06:35:04	error	chat/gpt35.go:70	Failed to get authorization: StatusCode: 401
> 
> 2024-04-18 06:35:04	error	chat/gpt35.go:71	If this error persists, your country may not be supported yet.
> 
> 2024-04-18 06:35:04	error	chat/gpt35.go:72	If your country was the issue, please consider using a U.S. PROXY.
> 
> ```
> 
> 但我区域已经选美国了

因存在授权池 存在刷新授权被拒的情况 如果不是不可用状态几条授权失败的情况正常 我计划加一个接口获取可用授权数的接口

池子大小 和 授权 可用次数可以调高一些
