### ISSUE TITLE
Pool GetGpt35 is empty

### ISSUE THREAD

**Issue by CherryLover** [aurorax-neo/free-gpt3.5-2api#18]
接口请求，返回 `Pool GetGpt35 is empty`，该如何刷新 session id 池呢

**Comment by aurorax-neo** [comment]
> 接口请求，返回 `Pool GetGpt35 is empty`，该如何刷新 session id 池呢

ip 不支持 换个ip 试试

**Comment by CherryLover** [comment]
好吧，谢谢回复了
