### ISSUE TITLE
4小时前更新后容器报错了

### ISSUE THREAD

**Issue by lostme01** [aurorax-neo/free-gpt3.5-2api#22]
2024-04-21 06:24:07     info    Gpt35Pool/Gpt35Pool.go:36       PoolMaxCount: 64, AuthExpirationDate: 600, Init Gpt35Pool...
2024-04-21 06:24:07     info    app/main.go:23  Server started on http://127.0.0.1:3040
panic: runtime error: index out of range [0] with length 0

goroutine 17 [running]:
free-gpt3.5-2api/ProxyPool.(*ProxyPool).GetProxy(...)
        /app/ProxyPool/ProxyPool.go:42
free-gpt3.5-2api/chat.NewGpt35()
        /app/chat/gpt35.go:72 +0x2b8
free-gpt3.5-2api/Gpt35Pool.(*Gpt35Pool).updateGpt35AtIndex(0xc0001284b0, 0x0)
        /app/Gpt35Pool/Gpt35Pool.go:110 +0x3d
free-gpt3.5-2api/Gpt35Pool.(*Gpt35Pool).updateGpt35Pool(...)
        /app/Gpt35Pool/Gpt35Pool.go:118
free-gpt3.5-2api/Gpt35Pool.(*Gpt35Pool).timingUpdateGpt35Pool(0xc0001284b0, 0xc000388c60?)
        /app/Gpt35Pool/Gpt35Pool.go:86 +0x72
created by free-gpt3.5-2api/Gpt35Pool.GetGpt35PoolInstance.func1 in goroutine 1
        /app/Gpt35Pool/Gpt35Pool.go:38 +0x1da
root@Japan02:~#

**Comment by aurorax-neo** [comment]
> 2024-04-21 06:24:07 info Gpt35Pool/Gpt35Pool.go:36 PoolMaxCount: 64, AuthExpirationDate: 600, Init Gpt35Pool... 2024-04-21 06:24:07 info app/main.go:23 Server started on http://127.0.0.1:3040 panic: runtime error: index out of range [0] with length 0
> 
> goroutine 17 [running]: free-gpt3.5-2api/ProxyPool.(*ProxyPool).GetProxy(...) /app/ProxyPool/ProxyPool.go:42 free-gpt3.5-2api/chat.NewGpt35() /app/chat/gpt35.go:72 +0x2b8 free-gpt3.5-2api/Gpt35Pool.(*Gpt35Pool).updateGpt35AtIndex(0xc0001284b0, 0x0) /app/Gpt35Pool/Gpt35Pool.go:110 +0x3d free-gpt3.5-2api/Gpt35Pool.(*Gpt35Pool).updateGpt35Pool(...) /app/Gpt35Pool/Gpt35Pool.go:118 free-gpt3.5-2api/Gpt35Pool.(*Gpt35Pool).timingUpdateGpt35Pool(0xc0001284b0, 0xc000388c60?) /app/Gpt35Pool/Gpt35Pool.go:86 +0x72 created by free-gpt3.5-2api/Gpt35Pool.GetGpt35PoolInstance.func1 in goroutine 1 /app/Gpt35Pool/Gpt35Pool.go:38 +0x1da root@Japan02:~#

拉最新的镜像，release-v0.0.8版本出了代理为空的 bug，release-v0.0.9已经修复

**Comment by lostme01** [comment]
好的
