### ISSUE TITLE
能配置给chatGPT Next Web吗？

### ISSUE THREAD

**Issue by vc9988** [aurorax-neo/free-gpt3.5-2api#23]
接口地址该如何填写？填写http://X.X.X.X:3040不通过，为什么？

**Comment by aurorax-neo** [comment]
> 接口地址该如何填写？填写[http://X.X.X.X:3040不通过，为什么？](http://X.X.X.X:3040%E4%B8%8D%E9%80%9A%E8%BF%87%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%EF%BC%9F)

部署方式？具体什么表现？
