### ISSUE TITLE
刚更新的，还不好用吗？

### ISSUE THREAD

**Issue by David030111** [aurorax-neo/free-gpt3.5-2api#41]
"please restart the program、change the IP address、use a proxy to try again."

**Comment by aurorax-neo** [comment]
> "please restart the program、change the IP address、use a proxy to try again."

暂时有问题 我抽空修 找一个可用的旧版本用

**Comment by David030111** [comment]
静候佳音！

**Comment by aurorax-neo** [comment]
> 静候佳音！

https://github.com/aurorax-neo/free-gpt3.5-2api/issues/42

风控很高现在 暂无解决办法 上代理试试吧
