### ISSUE TITLE
请问docker部署如何设置环境变量，不支持docker格式的环境变量吗？

### ISSUE THREAD

**Issue by WangShuXian6** [aurorax-neo/free-gpt3.5-2api#43]
是要进去容器改go的代码吗？

**Comment by aurorax-neo** [comment]
> 是要进去容器改go的代码吗？

使用 -e 参数
docker run -e "LOG_LEVEL=info"

**Comment by aurorax-neo** [comment]
> > 是要进去容器改go的代码吗？
> 
> 支持 使用 -e 参数 docker run -e "LOG_LEVEL=info"

**Comment by WangShuXian6** [comment]
```bash
docker run -itd  --name=free-gpt3.5-2api -p 9846:3040 -e PROXY="http://127.0.0.1:10809,http://127.0.0.1:10809" -e AUTHORIZATIONS="123456" ghcr.io/aurorax-neo/free-gpt3.5-2api 
```
![image](https://github.com/aurorax-neo/free-gpt3.5-2api/assets/30850497/2ecae009-6e17-437d-bcc9-8ba8e16c536c)

我这个代理支持gpt,但是今天开始出现真人验证了，是不是这个原因？

**Comment by aurorax-neo** [comment]
> ```bash
> 
> docker run -itd  --name=free-gpt3.5-2api -p 9846:3040 -e PROXY="http://127.0.0.1:10809,http://127.0.0.1:10809" -e AUTHORIZATIONS="123456" ghcr.io/aurorax-neo/free-gpt3.5-2api 
> 
> ```
> 
> ![image](https://github.com/aurorax-neo/free-gpt3.5-2api/assets/30850497/2ecae009-6e17-437d-bcc9-8ba8e16c536c)
> 
> 
> 
> 我这个代理支持gpt,但是今天开始出现真人验证了，是不是这个原因？

是的 今天封控拉高了 请求几次就会 429
