### ISSUE TITLE
部署了Koyeb，请问该如何使用呢？

### ISSUE THREAD

**Issue by hiflychat** [aurorax-neo/free-gpt3.5-2api#52]
API KEY: ?
API URL: ?
API URL PATH: ?

THANKS!

**Comment by aurorax-neo** [comment]
> API KEY: ? API URL: ? API URL PATH: ?
> 
> THANKS!

抱歉，我不太明白您的问题，现在 koyeb已不支持免登录  如果想用请配合代理使用

**Comment by hiflychat** [comment]
谢谢大佬的回复,我是小白,我想用在openai-translator 上,就是那些网站和key该怎么填写:
![1714561640428](https://github.com/aurorax-neo/free-gpt3.5-2api/assets/129601357/ce678876-cce2-4e40-be4e-55fd6055dd5a)

**Comment by aurorax-neo** [comment]
> 谢谢大佬的回复,我是小白,我想用在openai-translator 上,就是那些地址和key该怎么填写:
> 
> ![1714561640428](https://github.com/aurorax-neo/free-gpt3.5-2api/assets/129601357/ce678876-cce2-4e40-be4e-55fd6055dd5a)
> 
> 

apiurl 填 你的 http://ip:端口
