### ISSUE TITLE
content的内容太长会导致输出的content空白

### ISSUE THREAD

**Issue by wen495033653** [aurorax-neo/free-gpt3.5-2api#59]
content的内容太长会导致输出的content空白

**Comment by aurorax-neo** [comment]
> content的内容太长会导致输出的content空白

能否再详细一些？ 方便我复现一下，我自己暂时没遇到超长文本.

**Comment by wen495033653** [comment]
好的，json如下

{
    "model": "gpt-3.5-turbo",
    "messages": [
         {
            "role": "system",
            "content": "翻译user的vtt格式的内容，要求格式不变，只翻译文字部分，其他部分不变，把内容翻译成语言zh_tw"
        },
        {
            "role": "user",
            "content": "WEBVTT\n\n00:00:00.600 --> 00:00:02.860\n哎算了做就做吧\n\n00:00:02.920 --> 00:00:05.340\n反正我也是来公司锻炼的\n\n00:00:13.120 --> 00:00:14.060\n哎秘密\n\n00:00:15.200 --> 00:00:17.960\n我们公司附近新开了一家自助餐厅\n\n00:00:17.960 --> 00:00:19.920\n你有没有兴趣我们一起去啊\n\n00:00:19.920 --> 00:00:23.020\n对对对下了班咱一块去逛逛街吧\n\n00:00:23.520 --> 00:00:25.540\n好啊一起去吧\n\n00:00:26.120 --> 00:00:26.920\n走走走\n\n00:00:28.520 --> 00:00:31.300\n哎呀你小心着点\n\n00:00:31.320 --> 00:00:33.960\n弄脏了敏敏的衣服你可赔不起\n\n00:00:33.960 --> 00:00:37.020\n哎小丽这话你就说错了\n\n00:00:37.400 --> 00:00:39.100\n人家可本事的很\n\n00:00:39.200 --> 00:00:42.900\n随便勾勾手指头能换来一栋别墅呢\n\n00:00:43.360 --> 00:00:44.860\n怎么可能赔不起啊\n\n00:00:45.360 --> 00:00:46.560\n你什么意思啊\n\n00:00:46.560 --> 00:00:47.900\n什么意思\n\n00:00:48.240 --> 00:00:50.520\n你干的那点龌龊事呀\n\n00:00:50.520 --> 00:00:52.640\n我们可全都知道了\n\n00:00:52.640 --> 00:00:53.960\n你胡说八道什么\n\n00:00:53.960 --> 00:00:54.940\n我听不懂\n\n00:00:55.360 --> 00:00:58.120\n怎么敢做不敢当呀\n\n00:00:58.120 --> 00:00:59.640\n真是个贱货\n\n00:00:59.640 --> 00:01:02.800\n你行了别和他废话了\n\n00:01:02.800 --> 00:01:05.100\n走吧我们去吃饭吧\n\n00:01:05.200 --> 00:01:07.060\n饿了走走\n\n00:01:18.800 --> 00:01:21.980\n这小三该不会是一晚上睡在公司吧"
        }
    ],
    "stream": false
}

**Comment by aurorax-neo** [comment]
> 好的，json如下
> 
> { "model": "gpt-3.5-turbo", "messages": [ { "role": "system", "content": "翻译user的vtt格式的内容，要求格式不变，只翻译文字部分，其他部分不变，把内容翻译成语言zh_tw" }, { "role": "user", "content": "WEBVTT\n\n00:00:00.600 --> 00:00:02.860\n哎算了做就做吧\n\n00:00:02.920 --> 00:00:05.340\n反正我也是来公司锻炼的\n\n00:00:13.120 --> 00:00:14.060\n哎秘密\n\n00:00:15.200 --> 00:00:17.960\n我们公司附近新开了一家自助餐厅\n\n00:00:17.960 --> 00:00:19.920\n你有没有兴趣我们一起去啊\n\n00:00:19.920 --> 00:00:23.020\n对对对下了班咱一块去逛逛街吧\n\n00:00:23.520 --> 00:00:25.540\n好啊一起去吧\n\n00:00:26.120 --> 00:00:26.920\n走走走\n\n00:00:28.520 --> 00:00:31.300\n哎呀你小心着点\n\n00:00:31.320 --> 00:00:33.960\n弄脏了敏敏的衣服你可赔不起\n\n00:00:33.960 --> 00:00:37.020\n哎小丽这话你就说错了\n\n00:00:37.400 --> 00:00:39.100\n人家可本事的很\n\n00:00:39.200 --> 00:00:42.900\n随便勾勾手指头能换来一栋别墅呢\n\n00:00:43.360 --> 00:00:44.860\n怎么可能赔不起啊\n\n00:00:45.360 --> 00:00:46.560\n你什么意思啊\n\n00:00:46.560 --> 00:00:47.900\n什么意思\n\n00:00:48.240 --> 00:00:50.520\n你干的那点龌龊事呀\n\n00:00:50.520 --> 00:00:52.640\n我们可全都知道了\n\n00:00:52.640 --> 00:00:53.960\n你胡说八道什么\n\n00:00:53.960 --> 00:00:54.940\n我听不懂\n\n00:00:55.360 --> 00:00:58.120\n怎么敢做不敢当呀\n\n00:00:58.120 --> 00:00:59.640\n真是个贱货\n\n00:00:59.640 --> 00:01:02.800\n你行了别和他废话了\n\n00:01:02.800 --> 00:01:05.100\n走吧我们去吃饭吧\n\n00:01:05.200 --> 00:01:07.060\n饿了走走\n\n00:01:18.800 --> 00:01:21.980\n这小三该不会是一晚上睡在公司吧" } ], "stream": false }

已经复现  

其中有一条 消息是
{"type": "moderation", "conversation_id": "c357f7bf-cded-4629-b7de-a25ca919d9c2", "message_id": "a85522cd-47bd-40ba-9fac-33fe7fd6ab73", "is_completion": false, "moderation_response": {"flagged": false, "disclaimers": [], "blocked": true, "moderation_id": "modr-9MEOvjnCEponGWwCNafGqDHQTrNq7"}}

暂时还未知原因，可能后续会查找出原因，暂时 从  "blocked": true, "moderation_id": "modr-9MEOvjnCEponGWwCNafGqDHQTrNq7" 猜测是被审核机制阻止了

**Comment by wen495033653** [comment]
> > 好的，json如下
> > { "model": "gpt-3.5-turbo", "messages": [ { "role": "system", "content": "翻译user的vtt格式的内容，要求格式不变，只翻译文字部分，其他部分不变，把内容翻译成语言zh_tw" }, { "role": "user", "content": "WEBVTT\n\n00:00:00.600 --> 00:00:02.860\n哎算了做就做吧\n\n00:00:02.920 --> 00:00:05.340\n反正我也是来公司锻炼的\n\n00:00:13.120 --> 00:00:14.060\n哎秘密\n\n00:00:15.200 --> 00:00:17.960\n我们公司附近新开了一家自助餐厅\n\n00:00:17.960 --> 00:00:19.920\n你有没有兴趣我们一起去啊\n\n00:00:19.920 --> 00:00:23.020\n对对对下了班咱一块去逛逛街吧\n\n00:00:23.520 --> 00:00:25.540\n好啊一起去吧\n\n00:00:26.120 --> 00:00:26.920\n走走走\n\n00:00:28.520 --> 00:00:31.300\n哎呀你小心着点\n\n00:00:31.320 --> 00:00:33.960\n弄脏了敏敏的衣服你可赔不起\n\n00:00:33.960 --> 00:00:37.020\n哎小丽这话你就说错了\n\n00:00:37.400 --> 00:00:39.100\n人家可本事的很\n\n00:00:39.200 --> 00:00:42.900\n随便勾勾手指头能换来一栋别墅呢\n\n00:00:43.360 --> 00:00:44.860\n怎么可能赔不起啊\n\n00:00:45.360 --> 00:00:46.560\n你什么意思啊\n\n00:00:46.560 --> 00:00:47.900\n什么意思\n\n00:00:48.240 --> 00:00:50.520\n你干的那点龌龊事呀\n\n00:00:50.520 --> 00:00:52.640\n我们可全都知道了\n\n00:00:52.640 --> 00:00:53.960\n你胡说八道什么\n\n00:00:53.960 --> 00:00:54.940\n我听不懂\n\n00:00:55.360 --> 00:00:58.120\n怎么敢做不敢当呀\n\n00:00:58.120 --> 00:00:59.640\n真是个贱货\n\n00:00:59.640 --> 00:01:02.800\n你行了别和他废话了\n\n00:01:02.800 --> 00:01:05.100\n走吧我们去吃饭吧\n\n00:01:05.200 --> 00:01:07.060\n饿了走走\n\n00:01:18.800 --> 00:01:21.980\n这小三该不会是一晚上睡在公司吧" } ], "stream": false }
> 
> 已经复现
> 
> 其中有一条 消息是 {"type": "moderation", "conversation_id": "c357f7bf-cded-4629-b7de-a25ca919d9c2", "message_id": "a85522cd-47bd-40ba-9fac-33fe7fd6ab73", "is_completion": false, "moderation_response": {"flagged": false, "disclaimers": [], "blocked": true, "moderation_id": "modr-9MEOvjnCEponGWwCNafGqDHQTrNq7"}}
> 
> 暂时还未知原因，可能后续会查找出原因，暂时 从 "blocked": true, "moderation_id": "modr-9MEOvjnCEponGWwCNafGqDHQTrNq7" 猜测是被审核机制阻止了

应该是审核机制的原因，但是网页版免费版不会触发这个block

**Comment by wen495033653** [comment]
> > 好的，json如下
> > { "model": "gpt-3.5-turbo", "messages": [ { "role": "system", "content": "翻译user的vtt格式的内容，要求格式不变，只翻译文字部分，其他部分不变，把内容翻译成语言zh_tw" }, { "role": "user", "content": "WEBVTT\n\n00:00:00.600 --> 00:00:02.860\n哎算了做就做吧\n\n00:00:02.920 --> 00:00:05.340\n反正我也是来公司锻炼的\n\n00:00:13.120 --> 00:00:14.060\n哎秘密\n\n00:00:15.200 --> 00:00:17.960\n我们公司附近新开了一家自助餐厅\n\n00:00:17.960 --> 00:00:19.920\n你有没有兴趣我们一起去啊\n\n00:00:19.920 --> 00:00:23.020\n对对对下了班咱一块去逛逛街吧\n\n00:00:23.520 --> 00:00:25.540\n好啊一起去吧\n\n00:00:26.120 --> 00:00:26.920\n走走走\n\n00:00:28.520 --> 00:00:31.300\n哎呀你小心着点\n\n00:00:31.320 --> 00:00:33.960\n弄脏了敏敏的衣服你可赔不起\n\n00:00:33.960 --> 00:00:37.020\n哎小丽这话你就说错了\n\n00:00:37.400 --> 00:00:39.100\n人家可本事的很\n\n00:00:39.200 --> 00:00:42.900\n随便勾勾手指头能换来一栋别墅呢\n\n00:00:43.360 --> 00:00:44.860\n怎么可能赔不起啊\n\n00:00:45.360 --> 00:00:46.560\n你什么意思啊\n\n00:00:46.560 --> 00:00:47.900\n什么意思\n\n00:00:48.240 --> 00:00:50.520\n你干的那点龌龊事呀\n\n00:00:50.520 --> 00:00:52.640\n我们可全都知道了\n\n00:00:52.640 --> 00:00:53.960\n你胡说八道什么\n\n00:00:53.960 --> 00:00:54.940\n我听不懂\n\n00:00:55.360 --> 00:00:58.120\n怎么敢做不敢当呀\n\n00:00:58.120 --> 00:00:59.640\n真是个贱货\n\n00:00:59.640 --> 00:01:02.800\n你行了别和他废话了\n\n00:01:02.800 --> 00:01:05.100\n走吧我们去吃饭吧\n\n00:01:05.200 --> 00:01:07.060\n饿了走走\n\n00:01:18.800 --> 00:01:21.980\n这小三该不会是一晚上睡在公司吧" } ], "stream": false }
> 
> 已经复现
> 
> 其中有一条 消息是 {"type": "moderation", "conversation_id": "c357f7bf-cded-4629-b7de-a25ca919d9c2", "message_id": "a85522cd-47bd-40ba-9fac-33fe7fd6ab73", "is_completion": false, "moderation_response": {"flagged": false, "disclaimers": [], "blocked": true, "moderation_id": "modr-9MEOvjnCEponGWwCNafGqDHQTrNq7"}}
> 
> 暂时还未知原因，可能后续会查找出原因，暂时 从 "blocked": true, "moderation_id": "modr-9MEOvjnCEponGWwCNafGqDHQTrNq7" 猜测是被审核机制阻止了

请问"blocked": true这个响应值从哪里获取

**Comment by aurorax-neo** [comment]
> > > 好的，json如下
> > > { "model": "gpt-3.5-turbo", "messages": [ { "role": "system", "content": "翻译user的vtt格式的内容，要求格式不变，只翻译文字部分，其他部分不变，把内容翻译成语言zh_tw" }, { "role": "user", "content": "WEBVTT\n\n00:00:00.600 --> 00:00:02.860\n哎算了做就做吧\n\n00:00:02.920 --> 00:00:05.340\n反正我也是来公司锻炼的\n\n00:00:13.120 --> 00:00:14.060\n哎秘密\n\n00:00:15.200 --> 00:00:17.960\n我们公司附近新开了一家自助餐厅\n\n00:00:17.960 --> 00:00:19.920\n你有没有兴趣我们一起去啊\n\n00:00:19.920 --> 00:00:23.020\n对对对下了班咱一块去逛逛街吧\n\n00:00:23.520 --> 00:00:25.540\n好啊一起去吧\n\n00:00:26.120 --> 00:00:26.920\n走走走\n\n00:00:28.520 --> 00:00:31.300\n哎呀你小心着点\n\n00:00:31.320 --> 00:00:33.960\n弄脏了敏敏的衣服你可赔不起\n\n00:00:33.960 --> 00:00:37.020\n哎小丽这话你就说错了\n\n00:00:37.400 --> 00:00:39.100\n人家可本事的很\n\n00:00:39.200 --> 00:00:42.900\n随便勾勾手指头能换来一栋别墅呢\n\n00:00:43.360 --> 00:00:44.860\n怎么可能赔不起啊\n\n00:00:45.360 --> 00:00:46.560\n你什么意思啊\n\n00:00:46.560 --> 00:00:47.900\n什么意思\n\n00:00:48.240 --> 00:00:50.520\n你干的那点龌龊事呀\n\n00:00:50.520 --> 00:00:52.640\n我们可全都知道了\n\n00:00:52.640 --> 00:00:53.960\n你胡说八道什么\n\n00:00:53.960 --> 00:00:54.940\n我听不懂\n\n00:00:55.360 --> 00:00:58.120\n怎么敢做不敢当呀\n\n00:00:58.120 --> 00:00:59.640\n真是个贱货\n\n00:00:59.640 --> 00:01:02.800\n你行了别和他废话了\n\n00:01:02.800 --> 00:01:05.100\n走吧我们去吃饭吧\n\n00:01:05.200 --> 00:01:07.060\n饿了走走\n\n00:01:18.800 --> 00:01:21.980\n这小三该不会是一晚上睡在公司吧" } ], "stream": false }
> > 
> > 
> > 已经复现
> > 其中有一条 消息是 {"type": "moderation", "conversation_id": "c357f7bf-cded-4629-b7de-a25ca919d9c2", "message_id": "a85522cd-47bd-40ba-9fac-33fe7fd6ab73", "is_completion": false, "moderation_response": {"flagged": false, "disclaimers": [], "blocked": true, "moderation_id": "modr-9MEOvjnCEponGWwCNafGqDHQTrNq7"}}
> > 暂时还未知原因，可能后续会查找出原因，暂时 从 "blocked": true, "moderation_id": "modr-9MEOvjnCEponGWwCNafGqDHQTrNq7" 猜测是被审核机制阻止了
> 
> 请问"blocked": true这个响应值从哪里获取

{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "system",
            "content": "翻译user的vtt格式的内容，要求格式不变，只翻译文字部分，其他部分不变，把内容翻译成语言zh_tw"
        },
        {
            "role": "user",
            "content": "WEBVTT\n\n00:00:00.600 --> 00:00:02.860\n哎算了做就做吧\n\n00:00:02.920 --> 00:00:05.340\n反正我也是来公司锻炼的\n\n00:00:13.120 --> 00:00:14.060\n哎秘密\n\n00:00:15.200 --> 00:00:17.960\n我们公司附近新开了一家自助餐厅\n\n00:00:17.960 --> 00:00:19.920\n你有没有兴趣我们一起去啊\n\n00:00:19.920 --> 00:00:23.020\n对对对下了班咱一块去逛逛街吧\n\n00:00:23.520 --> 00:00:25.540\n好啊一起去吧\n\n00:00:26.120 --> 00:00:26.920\n走走走\n\n00:00:28.520 --> 00:00:31.300\n哎呀你小心着点\n\n00:00:31.320 --> 00:00:33.960\n弄脏了敏敏的衣服你可赔不起\n\n00:00:33.960 --> 00:00:37.020\n哎小丽这话你就说错了\n\n00:00:37.400 --> 00:00:39.100\n人家可本事的很\n\n00:00:39.200 --> 00:00:42.900\n随便勾勾手指头能换来一栋别墅呢\n\n00:00:43.360 --> 00:00:44.860\n怎么可能赔不起啊\n\n00:00:45.360 --> 00:00:46.560\n你什么意思啊\n\n00:00:46.560 --> 00:00:47.900\n什么意思\n\n00:00:48.240 --> 00:00:50.520\n你干的那点龌龊事呀\n\n00:00:50.520 --> 00:00:52.640\n我们可全都知道了\n\n00:00:52.640 --> 00:00:53.960\n你胡说八道什么\n\n00:00:53.960 --> 00:00:54.940\n我听不懂\n\n00:00:55.360 --> 00:00:58.120\n怎么敢做不敢当呀\n\n00:00:58.120 --> 00:00:59.640\n真是个贱货\n\n00:00:59.640 --> 00:01:02.800\n你行了别和他废话了\n\n00:01:02.800 --> 00:01:05.100\n走吧我们去吃饭吧\n\n00:01:05.200 --> 00:01:07.060\n饿了走走\n\n00:01:18.800 --> 00:01:21.980\n这小三该不会是一晚上睡在公司吧"
        }
    ],
    "stream": false
}

会被审核

{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "WEBVTT\n\n00:00:00.600 --> 00:00:02.860\n哎算了做就做吧\n\n00:00:02.920 --> 00:00:05.340\n反正我也是来公司锻炼的\n\n00:00:13.120 --> 00:00:14.060\n哎秘密\n\n00:00:15.200 --> 00:00:17.960\n我们公司附近新开了一家自助餐厅\n\n00:00:17.960 --> 00:00:19.920\n你有没有兴趣我们一起去啊\n\n00:00:19.920 --> 00:00:23.020\n对对对下了班咱一块去逛逛街吧\n\n00:00:23.520 --> 00:00:25.540\n好啊一起去吧\n\n00:00:26.120 --> 00:00:26.920\n走走走\n\n00:00:28.520 --> 00:00:31.300\n哎呀你小心着点\n\n00:00:31.320 --> 00:00:33.960\n弄脏了敏敏的衣服你可赔不起\n\n00:00:33.960 --> 00:00:37.020\n哎小丽这话你就说错了\n\n00:00:37.400 --> 00:00:39.100\n人家可本事的很\n\n00:00:39.200 --> 00:00:42.900\n随便勾勾手指头能换来一栋别墅呢\n\n00:00:43.360 --> 00:00:44.860\n怎么可能赔不起啊\n\n00:00:45.360 --> 00:00:46.560\n你什么意思啊\n\n00:00:46.560 --> 00:00:47.900\n什么意思\n\n00:00:48.240 --> 00:00:50.520\n你干的那点龌龊事呀\n\n00:00:50.520 --> 00:00:52.640\n我们可全都知道了\n\n00:00:52.640 --> 00:00:53.960\n你胡说八道什么\n\n00:00:53.960 --> 00:00:54.940\n我听不懂\n\n00:00:55.360 --> 00:00:58.120\n怎么敢做不敢当呀\n\n00:00:58.120 --> 00:00:59.640\n真是个贱货\n\n00:00:59.640 --> 00:01:02.800\n你行了别和他废话了\n\n00:01:02.800 --> 00:01:05.100\n走吧我们去吃饭吧\n\n00:01:05.200 --> 00:01:07.060\n饿了走走\n\n00:01:18.800 --> 00:01:21.980\n这小三该不会是一晚上睡在公司吧     翻译user的vtt格式的内容，要求格式不变，只翻译文字部分，其他部分不变，把内容翻译成语言zh_tw"
        }
    ],
    "stream": false
}

不会被审核，system 起到了作用
