### ISSUE TITLE
大佬，401错误怎么处理

### ISSUE THREAD

**Issue by sdlkhfksl** [aurorax-neo/free-gpt3.5-2api#61]
{
  "detail": {
    "code": 401,
    "msg": "please restart the program、change the IP address、use a proxy to try again.",
    "error": null
  }
}

**Comment by aurorax-neo** [comment]
> {
> 
>   "detail": {
> 
>     "code": 401,
> 
>     "msg": "please restart the program、change the IP address、use a proxy to try again.",
> 
>     "error": null
> 
>   }
> 
> }
> 
> 

如 msg，换机器或者代理试试
