### ISSUE TITLE
modelMapping的模型问题

### ISSUE THREAD

**Issue by wen495033653** [aurorax-neo/free-gpt3.5-2api#62]
模型不是text-davinci-003吗，还是说等价于text-davinci-002-render-sha

**Comment by aurorax-neo** [comment]
> 模型不是text-davinci-003吗，还是说等价于text-davinci-002-render-sha

我去了解一下 还是之前做的映射

![image](https://github.com/aurorax-neo/free-gpt3.5-2api/assets/83893968/452cf290-3823-4a52-aa49-c76a964c150b)

网页免登的请求参数
