### ISSUE TITLE
请教大哥们，如何给https://github.com/binary-husky/gpt_academic这个项目用

### ISSUE THREAD

**Issue by Dolphin4mi** [aurorax-neo/free-gpt3.5-2api#64]
请教大哥们，如何给https://github.com/binary-husky/gpt_academic这个项目用，感谢，学生都想白嫖

**Comment by aurorax-neo** [comment]
> 请教大哥们，如何给https://github.com/binary-husky/gpt_academic这个项目用，感谢，学生都想白嫖

看这个项目的文档 本项目只提供 免登录的 chat2api

**Comment by Dolphin4mi** [comment]
> > 请教大哥们，如何给[https://github.com/binary-husky/gpt_academic这个项目用，感谢，学生都想白嫖](https://github.com/binary-husky/gpt_academic%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E7%94%A8%EF%BC%8C%E6%84%9F%E8%B0%A2%EF%BC%8C%E5%AD%A6%E7%94%9F%E9%83%BD%E6%83%B3%E7%99%BD%E5%AB%96)
> 
> 看这个项目的文档 本项目只提供 免登录的 chat2api

感谢回复！我自己在vps上搭好了，在vps上curl可以得到响应，而在我实验室的电脑却无法得到任何响应，我怀疑是http访问被墙了，是否可以做成https的？

**Comment by aurorax-neo** [comment]
> > > 请教大哥们，如何给[https://github.com/binary-husky/gpt_academic这个项目用，感谢，学生都想白嫖](https://github.com/binary-husky/gpt_academic%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E7%94%A8%EF%BC%8C%E6%84%9F%E8%B0%A2%EF%BC%8C%E5%AD%A6%E7%94%9F%E9%83%BD%E6%83%B3%E7%99%BD%E5%AB%96)
> > 
> > 
> > 看这个项目的文档 本项目只提供 免登录的 chat2api
> 
> 感谢回复！我自己在vps上搭好了，在vps上curl可以得到响应，而在我实验室的电脑却无法得到任何响应，我怀疑是http访问被墙了，是否可以做成https的？

实验室的电脑ip能否访问oai，如果不可以请添加代理试一试，暂时解决方案先套一层 nginx 反代配置 https
