### ISSUE TITLE
能获取count，但是请求403

### ISSUE THREAD

**Issue by KinmoCode** [aurorax-neo/free-gpt3.5-2api#67]
{"detail":{"code":403,"msg":"Request error","error":null}}

**Comment by aurorax-neo** [comment]
> {"detail":{"code":403,"msg":"Request error","error":null}}

换个 ip 试试

**Comment by KinmoCode** [comment]
公司内网，好像换不了IP

**Comment by KinmoCode** [comment]
> > {"detail":{"code":403,"msg":"Request error","error":null}}
> 
> 换个 ip 试试

换了几个ip
{"detail":{"code":500,"msg":"RequestClient Do error","error":{"Op":"Post","URL":"https://chatgpt.com/backend-anon/conversation","Err":{}}}}
有遇到这种的

**Comment by aurorax-neo** [comment]
> > > {"detail":{"code":403,"msg":"Request error","error":null}}
> > 
> > 
> > 换个 ip 试试
> 
> 公司内网，好像换不了IP

公司内网可以 访问openai吗？ 国内的网络不行的

**Comment by KinmoCode** [comment]
> > > > {"detail":{"code":403,"msg":"Request error","error":null}}
> > > 
> > > 
> > > 换个 ip 试试
> > 
> > 
> > 公司内网，好像换不了IP
> 
> 公司内网可以 访问openai吗？ 国内的网络不行的

我有代理出去的，使用chatgpt是正常的

**Comment by aurorax-neo** [comment]
> > > > > {"detail":{"code":403,"msg":"Request error","error":null}}
> > > > 
> > > > 
> > > > 换个 ip 试试
> > > 
> > > 
> > > 公司内网，好像换不了IP
> > 
> > 
> > 公司内网可以 访问openai吗？ 国内的网络不行的
> 
> 我有代理出去的，使用chatgpt是正常的

那换个代理 不就是换ip 了，我这里测试正常，网络环境不同我无法做到全面测试

**Comment by KinmoCode** [comment]
> > > > > > {"detail":{"code":403,"msg":"Request error","error":null}}
> > > > > 
> > > > > 
> > > > > 换个 ip 试试
> > > > 
> > > > 
> > > > 公司内网，好像换不了IP
> > > 
> > > 
> > > 公司内网可以 访问openai吗？ 国内的网络不行的
> > 
> > 
> > 我有代理出去的，使用chatgpt是正常的
> 
> 那换个代理 不就是换ip 了，我这里测试正常，网络环境不同我无法做到全面测试

奇怪
http://localhost:9846/
Hello,This is free-gpt3.5-2api.

用api就403，哈哈
我再研究研究

**Comment by aurorax-neo** [comment]
> > > > > > > {"detail":{"code":403,"msg":"Request error","error":null}}
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > 换个 ip 试试
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 公司内网，好像换不了IP
> 
> > > > 
> 
> > > > 
> 
> > > > 公司内网可以 访问openai吗？ 国内的网络不行的
> 
> > > 
> 
> > > 
> 
> > > 我有代理出去的，使用chatgpt是正常的
> 
> > 
> 
> > 那换个代理 不就是换ip 了，我这里测试正常，网络环境不同我无法做到全面测试
> 
> 
> 
> 奇怪
> 
> http://localhost:9846/
> 
> Hello,This is free-gpt3.5-2api.
> 
> 
> 
> 用api就403，哈哈
> 
> 我再研究研究

免登录现在很高 ip 纯净度很重要，最近发现单 ip 限制了并发
