### ISSUE TITLE
咨询一下

### ISSUE THREAD

**Issue by David030111** [aurorax-neo/free-gpt3.5-2api#74]
{
    "detail": {
        "code": 401,
        "msg": "please restart the program、change the IP address、use a proxy to try again.",
        "error": null
    }
}

返回是这样的，怎么处理呢？

**Comment by aurorax-neo** [comment]
> {
> 
>     "detail": {
> 
>         "code": 401,
> 
>         "msg": "please restart the program、change the IP address、use a proxy to try again.",
> 
>         "error": null
> 
>     }
> 
> }
> 
> 
> 
> 返回是这样的，怎么处理呢？

更换 ip 或者使用账号请求，免登录现在风控很高

**Comment by David030111** [comment]
access-token我能获取到，AUTHORIZATIONS字段的ac-  是怎么获取的？我看写的是必须填写

**Comment by aurorax-neo** [comment]
> access-token我能获取到，AUTHORIZATIONS字段的ac- 是怎么获取的？我看写的是必须填写

想用内置的  access-token   就填写  ac-*******************************  这个自定义 

也可以 直接使用 access-token 调用
