### ISSUE TITLE
[求教]普通用户权限需求

### ISSUE THREAD

**Issue by molezz** [aurorax-neo/free-gpt3.5-2api#78]
普通用户运行提示
```
fileCache.IsExist err: stat /tmp/fake_useragent_0.2.0.json: permission denied
```
没有tmp权限，有什么方式指定~./目录吗？

**Comment by aurorax-neo** [comment]
> 普通用户运行提示
> 
> ```
> fileCache.IsExist err: stat /tmp/fake_useragent_0.2.0.json: permission denied
> ```
> 
> 没有tmp权限，有什么方式指定~./目录吗？

第一次看见反馈 我排查一下

**Comment by molezz** [comment]
> > 普通用户运行提示
> > ```
> > fileCache.IsExist err: stat /tmp/fake_useragent_0.2.0.json: permission denied
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 没有tmp权限，有什么方式指定~./目录吗？
> 
> 第一次看见反馈 我排查一下

这么有幸， 不急，有其他root机器。  也是因为duck api挂了…… freebsd测试，hahaha

**Comment by aurorax-neo** [comment]
> > > 普通用户运行提示
> > > ```
> > > fileCache.IsExist err: stat /tmp/fake_useragent_0.2.0.json: permission denied
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 没有tmp权限，有什么方式指定~./目录吗？
> > 
> > 
> > 第一次看见反馈 我排查一下
> 
> 这么有幸， 不急，有其他root机器。 也是因为duck api挂了…… freebsd测试，hahaha

release-v0.4.1 已经修复，等打包好重试一下，如有问题感谢反馈
