### ISSUE TITLE
看这个说明不会搭建，有视频或者文字教程吗？

### ISSUE THREAD

**Issue by Benson80** [aurorax-neo/free-gpt3.5-2api#83]

**Comment by Benson80** [comment]
出现这个提示：{"error":{"message":"未提供令牌 (request id: 20240628140959973355880OxCjVqB7)","type":"new_api_error"}}
令牌应该放在哪里？

**Comment by aurorax-neo** [comment]
> 出现这个提示：{"error":{"message":"未提供令牌 (request id: 20240628140959973355880OxCjVqB7)","type":"new_api_error"}} 令牌应该放在哪里？

![image](https://github.com/aurorax-neo/free-gpt3.5-2api/assets/83893968/0cddc4b5-5f3c-4277-bec7-aafab460f926)

access_token#{abc},{abc}替换为 AUTHORIZATIONS 内的任意一项

**Comment by gllgoe** [comment]
访问网站显示Hello,This is free-gpt3.5-2api.，在oneapi中测试显示 response status code 500，使用时也是：bad_response_status_code bad response status code 500 (request id: 2024070106371638913935585415016)，请问该如何解决？多谢大佬

**Comment by aurorax-neo** [comment]
> 访问网站显示Hello,This is free-gpt3.5-2api.，在oneapi中测试显示 response status code 500，使用时也是：bad_response_status_code bad response status code 500 (request id: 2024070106371638913935585415016)，请问该如何解决？多谢大佬

![image](https://github.com/aurorax-neo/free-gpt3.5-2api/assets/83893968/3b605aa1-11d3-47a4-abbc-660f5aa9294d)

可以提供一下具体日志吗，我测试 Vercel 和 docker 都没有问题

**Comment by jonntd** [comment]
Vercel 创建不了什么情况

**Comment by aurorax-neo** [comment]
> Vercel 创建不了什么情况

也报错500吗？有没有添加环境变量 AUTHORIZATIONS ？

**Comment by jonntd** [comment]
> > Vercel 创建不了什么情况
> 
> 也报错500吗？有没有添加环境变量 AUTHORIZATIONS ？

直接就没启动，我直接点下面的按钮创建的啥也没加

**Comment by gllgoe** [comment]
> > 访问网站显示Hello,This is free-gpt3.5-2api.，在oneapi中测试显示 response status code 500，使用时也是：bad_response_status_code bad response status code 500 (request id: 2024070106371638913935585415016)，请问该如何解决？多谢大佬
> 
> ![image](https://private-user-images.githubusercontent.com/83893968/344570895-3b605aa1-11d3-47a4-abbc-660f5aa9294d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODI0OTMsIm5iZiI6MTcxOTk4MjE5MywicGF0aCI6Ii84Mzg5Mzk2OC8zNDQ1NzA4OTUtM2I2MDVhYTEtMTFkMy00N2E0LWFiYmMtNjYwZjVhYTkyOTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA0NDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YmVmOTA0MmQxM2RiZTQ2YmY0YWQwYjlkMzA1NzgzY2QxNWVjNmFhNDM4ZDE0YmMzZjNmMDA4MDUyMTNkOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLilxABNYlj-jj48gmAEyvNfbln3zb9iECq8eMj_Vx0)
> 
> 可以提供一下具体日志吗，我测试 Vercel 和 docker 都没有问题

[INFO]2024/07/02 05:06:32 main.go:19 Server started on http://127.0.0.1:3040
[GIN] 2024/07/02 - 19:10:53 | 404 | 1.202µs | 52.167.144.59 | GET "/robots.txt"
[GIN] 2024/07/02 - 19:11:03 | 200 | 6.540914ms | 207.46.13.153 | GET "/"
[ERROR]2024/07/03 04:50:52 completions.go:51 ForceLogin: true
[GIN] 2024/07/03 - 04:50:52 | 500 | 2.132460772s | 218.205.46.237 | POST "/v1/chat/completions"
[GIN] 2024/07/03 - 04:51:50 | 404 | 671ns | 218.205.46.237 | POST "/v1/chat/completions/v1/chat/completions"
[GIN] 2024/07/03 - 04:51:52 | 404 | 551ns | 218.205.46.237 | POST "/v1/chat/completions/v1/chat/completions"
[GIN] 2024/07/03 - 04:52:08 | 404 | 591ns | 218.205.46.237 | POST "/v1/chat/completions/v1/chat/completions"
[ERROR]2024/07/03 04:54:21 completions.go:51 ForceLogin: true
[GIN] 2024/07/03 - 04:54:21 | 500 | 1.965513653s | 218.205.46.237 | POST "/v1/chat/completions"
[GIN] 2024/07/03 - 04:55:29 | 200 | 7.084339ms | 221.226.41.4 | GET "/"
[GIN] 2024/07/03 - 04:55:29 | 404 | 591ns | 221.226.41.4 | GET "/favicon.ico"
[GIN] 2024/07/03 - 04:56:07 | 404 | 591ns | 218.205.46.237 | POST "/v1/chat/completions/v1/chat/completions"
其中有用过按你图示的自定义代理，也有用过openai的

**Comment by aurorax-neo** [comment]
> /v1/chat/completions/v1/chat/completions

/v1/chat/completions/v1/chat/completions  请求路径 多了个 /v1/chat/completions

**Comment by gllgoe** [comment]
> > /v1/chat/completions/v1/chat/completions
> 
> /v1/chat/completions/v1/chat/completions 请求路径 多了个 /v1/chat/completions
按你的完整的加上的就多了 就反馈404，去掉就500

**Comment by GrahLnn** [comment]
```
root@vultr:~/free-gpt3.5-2api# curl --location --request GET 'http://127.0.0.1:9846/v1/accTokens' --header 'Authorization: Bearer ac-abc'
{"count":1,"canUseCount":1}
root@vultr:~/free-gpt3.5-2api# curl --location --request POST 'http://127.0.0.1:9846/v1/chat/completions' --header 'Authorization: Bearer ac-abc' --header 'Content-Type: application/json' --data-raw '{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "西红柿炒钢丝球怎么做?"
        }
    ],
    "stream": false
}'
{"detail":{"code":500,"msg":"StatusCode: 403","error":null}}
```
![image](https://github.com/aurorax-neo/free-gpt3.5-2api/assets/67181515/3236a27e-3631-4e07-9e92-99832114ab24)

我部署出来也有问题
