### ISSUE TITLE
报500

### ISSUE THREAD

**Issue by fan-stars** [aurorax-neo/free-gpt3.5-2api#85]
新版本部署后 报 500 是怎么回事呢

**Comment by aurorax-neo** [comment]
> 新版本部署后 报 500 是怎么回事呢

使用的是什么部署方式，可以多请求几次试试

**Comment by fan-stars** [comment]
可以了，新版本必须要设置 AUTHORIZATIONS，不设置就报500，老版本不需要设置

**Comment by aurorax-neo** [comment]
> 可以了，新版本必须要设置 AUTHORIZATIONS，不设置就报500，老版本不需要设置

是的，新版本强制设置AUTHORIZATIONS，防止接口被刷

**Comment by fan-stars** [comment]
好的 谢谢
