### ISSUE TITLE
大佬，帮忙看一下

### ISSUE THREAD

**Issue by David030111** [aurorax-neo/free-gpt3.5-2api#86]
我搭建好了，用的abc进行请求，返回如下：
{
    "detail": {
        "code": 500,
        "msg": "ForceLogin: true",
        "error": null
    }
}

是什么问题呢？

**Comment by aurorax-neo** [comment]
> 我搭建好了，用的abc进行请求，返回如下： { "detail": { "code": 500, "msg": "ForceLogin: true", "error": null } }
> 
> 是什么问题呢？

ip质量不行 换个好点的ip
