### ISSUE TITLE
和xqdoo00o/chatgpt-web一起，参数怎么填呢，谢谢

### ISSUE THREAD

**Issue by dyingway** [aurorax-neo/free-gpt3.5-2api#87]
> curl测试通过，但除了chatbox的应用中使用自定义API可以用。其他的只能选填在openai的API都无法使用。比如 [https://github.com/xqdoo00o/chatgpt-web](https://github.com/xqdoo00o/chatgpt)
的项目或者[https://github.com/ChatGPTNextWeb](https://github.com/ChatGPTNextWeb)
> 
> 请问可以告诉下怎么填写吗，谢谢作者。

**Comment by dyingway** [comment]
> curl测试通过，但除了chatbox的应用中使用自定义API可以用。其他的只能选填在openai的API都无法使用。比如 [https://github.com/xqdoo00o/chatgpt-web](https://github.com/xqdoo00o/chatgpt)
的项目或者[https://github.com/ChatGPTNextWeb](https://github.com/ChatGPTNextWeb)
> 
> 请问可以告诉下怎么填写吗，谢谢作者。

**Comment by aurorax-neo** [comment]
> > curl测试通过，但除了chatbox的应用中使用自定义API可以用。其他的只能选填在openai的API都无法使用。比如 [https://github.com/xqdoo00o/chatgpt-web](https://github.com/xqdoo00o/chatgpt)
> > 的项目或者https://github.com/ChatGPTNextWeb
> > 请问可以告诉下怎么填写吗，谢谢作者。

暂时先套着 one-api 使用  有些请求细节没有处理

**Comment by dyingway** [comment]
好的，谢谢，我去看下one-api。
