### ISSUE TITLE
大佬，能不能科普下部署到vercel之后

### ISSUE THREAD

**Issue by city10666** [aurorax-neo/free-gpt3.5-2api#88]
科普下部署到vercel之后，添加哪些变量？还是不用添加？！！！

**Comment by aurorax-neo** [comment]
> 科普下部署到vercel之后，添加哪些变量？还是不用添加？！！！

![image](https://github.com/aurorax-neo/free-gpt3.5-2api/assets/83893968/d88a055c-d773-45d5-b5a3-fd4e437ca9ff)
标注必须需要填写 其它根据需要填写
