### ISSUE TITLE
TOKENS_FILE文件目录在哪呢?

### ISSUE THREAD

**Issue by SoulGolf** [aurorax-neo/free-gpt3.5-2api#89]
我在docker容器的app新建了这个文件配置好,docker环境变量也配置好名称,但是后驱token一直为0

**Comment by aurorax-neo** [comment]
> 我在docker容器的app新建了这个文件配置好,docker环境变量也配置好名称,但是后驱token一直为0

默认与程序在相同文件夹

**Comment by SoulGolf** [comment]
> > 我在docker容器的app新建了这个文件配置好,docker环境变量也配置好名称,但是后驱token一直为0
> 
> 默认与程序在相同文件夹

我docker直接启动的,没有使用compose,我在docker容器中/app创建了没有生效

**Comment by aurorax-neo** [comment]
> > > 我在docker容器的app新建了这个文件配置好,docker环境变量也配置好名称,但是后驱token一直为0
> > 
> > 
> > 默认与程序在相同文件夹
> 
> 我docker直接启动的,没有使用compose,我在docker容器中/app创建了没有生效

tokens.yml  这个文件 不是 tokens.yaml

**Comment by SoulGolf** [comment]
> > > > 我在docker容器的app新建了这个文件配置好,docker环境变量也配置好名称,但是后驱token一直为0
> > > 
> > > 
> > > 默认与程序在相同文件夹
> > 
> > 
> > 我docker直接启动的,没有使用compose,我在docker容器中/app创建了没有生效
> 
> tokens.yml 这个文件 不是 tokens.yaml

我是使用的tokens.yml

**Comment by aurorax-neo** [comment]
> > > > > 我在docker容器的app新建了这个文件配置好,docker环境变量也配置好名称,但是后驱token一直为0
> 
> > > > 
> 
> > > > 
> 
> > > > 默认与程序在相同文件夹
> 
> > > 
> 
> > > 
> 
> > > 我docker直接启动的,没有使用compose,我在docker容器中/app创建了没有生效
> 
> > 
> 
> > tokens.yml 这个文件 不是 tokens.yaml
> 
> 
> 
> 我是使用的tokens.yml

有可能存在 bug 暂时没有时间排查

**Comment by maolei1024** [comment]
这里是docker镜像构建完后/app下就只剩下程序本体了,你可以直接把这个token的文件挂载到docker内部,或者每次docker cp拷贝进去一份
