### ISSUE TITLE
302 错误: completions.go:51 StatusCode: 302

### ISSUE THREAD

**Issue by maolei1024** [aurorax-neo/free-gpt3.5-2api#93]
LOG_LEVEL使用的debug
每次对话出现如下信息
``` 
[INFO]2024/11/14 04:18:30 main.go:19 Server started on http://127.0.0.1:3040
[ERROR]2024/11/14 04:18:42 completions.go:51 StatusCode: 302
[GIN] 2024/11/14 - 04:18:42 | 500 |  6.202924564s |     172.18.0.13 | POST     "/v1/chat/completions"
[ERROR]2024/11/14 04:18:54 completions.go:51 StatusCode: 302
[GIN] 2024/11/14 - 04:18:54 | 500 | 11.368444439s |     172.18.0.13 | POST     "/v1/chat/completions"

```
使用的docker部署,并且配置了代理(我使用代理可以打开网页并进行对话)

终端命令和返回值如下
```
curl --location --request POST 'http://127.0.0.1:7846/v1/chat/completions' \                                                                                                                                                ─╯
--header 'Authorization: Bearer ac-maolei' \
--header 'Content-Type: application/json' \
--data-raw '{
    "model": "auto",         
    "messages": [
        {
            "role": "user",
            "content": "西红柿炒钢丝球怎么做?"
        }
    ],
    "stream": false
}'
> {"detail":{"code":500,"msg":"StatusCode: 302","error":null}}

```

请问如何解决

**Comment by aurorax-neo** [comment]
> LOG_LEVEL使用的debug
> 
> 每次对话出现如下信息
> 
> ``` 
> 
> [INFO]2024/11/14 04:18:30 main.go:19 Server started on http://127.0.0.1:3040
> 
> [ERROR]2024/11/14 04:18:42 completions.go:51 StatusCode: 302
> 
> [GIN] 2024/11/14 - 04:18:42 | 500 |  6.202924564s |     172.18.0.13 | POST     "/v1/chat/completions"
> 
> [ERROR]2024/11/14 04:18:54 completions.go:51 StatusCode: 302
> 
> [GIN] 2024/11/14 - 04:18:54 | 500 | 11.368444439s |     172.18.0.13 | POST     "/v1/chat/completions"
> 
> 
> 
> ```
> 
> 使用的docker部署,并且配置了代理(我使用代理可以打开网页并进行对话)
> 
> 
> 
> 终端命令和返回值如下
> 
> ```
> 
> curl --location --request POST 'http://127.0.0.1:7846/v1/chat/completions' \                                                                                                                                                ─╯
> 
> --header 'Authorization: Bearer ac-maolei' \
> 
> --header 'Content-Type: application/json' \
> 
> --data-raw '{
> 
>     "model": "auto",         
> 
>     "messages": [
> 
>         {
> 
>             "role": "user",
> 
>             "content": "西红柿炒钢丝球怎么做?"
> 
>         }
> 
>     ],
> 
>     "stream": false
> 
> }'
> 
> > {"detail":{"code":500,"msg":"StatusCode: 302","error":null}}
> 
> 
> 
> ```
> 
> 
> 
> 请问如何解决

好久没修复了，可能 oai 风控调整了

**Comment by maolei1024** [comment]
好的,那我放弃挣扎了😂
