### ISSUE TITLE
vercel部署后404 page not found

### ISSUE THREAD

**Issue by kiw-jpg** [aurorax-neo/free-gpt3.5-2api#95]
vercel部署后，打开https://xxxxx.vercel.app/v1/chat/completions,显示404 page not found

是不是不能用？

**Comment by aurorax-neo** [comment]
> vercel部署后，打开https://xxxxx.vercel.app/v1/chat/completions,显示404 page not found
> 
> 
> 
> 是不是不能用？

大概率不能用了，现在 api 很多，维护这个收益不大，官方还在疯狂降智

**Comment by kiw-jpg** [comment]
> > vercel部署后，打开[https://xxxxx.vercel.app/v1/chat/completions,显示404](https://xxxxx.vercel.app/v1/chat/completions,%E6%98%BE%E7%A4%BA404) page not found
> > 是不是不能用？
> 
> 大概率不能用了，现在 api 很多，维护这个收益不大，官方还在疯狂降智

求推荐个api

**Comment by aurorax-neo** [comment]
> > > vercel部署后，打开[https://xxxxx.vercel.app/v1/chat/completions,显示404](https://xxxxx.vercel.app/v1/chat/completions,%E6%98%BE%E7%A4%BA404) page not found
> > > 是不是不能用？
> > 
> > 
> > 大概率不能用了，现在 api 很多，维护这个收益不大，官方还在疯狂降智
> 
> 求推荐个api

google  deepseek  硅基流动
